# Docker compose for whole ec2 setup
# nodejs server
# nginx server
# node exporter
# cadvisor
# prometheus
# grafana later if we resources allow it

version: "3.9"
services:
  sirius-crm-server:
    image: 081009271230.dkr.ecr.eu-central-1.amazonaws.com/sirius-crm-server:${IMAGE_TAG}
    container_name: sirius-crm-server
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    mem_limit: 192m
    cpus: 0.1
  nginx:
    image: nginx:1.29.4-alpine-perl
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.prometheus_pass:/etc/nginx/.prometheus_pass:ro
    depends_on:
      - sirius-crm-server
    restart: unless-stopped
    mem_limit: 64m
    cpus: 0.05

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter
    restart: unless-stopped
    network_mode: "host"
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    mem_limit: 64m
    cpus: 0.1
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    command:
      - "--housekeeping_interval=30s"
    mem_limit: 128m
    cpus: 0.15

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/recording_rules.yml:/etc/prometheus/recording_rules.yml:ro
      - ./prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.size=500MB"
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.2
