global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:8080"]

rule_files:
  - "/etc/prometheus/recording_rules.yml"
