name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm test
      - run: npm run build

  deploy-render:
    needs: unit-tests
    if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: render
    env:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
    steps:
      - name: Trigger Render deploy
        run: |
          response=$(curl -s -w "%{http_code}" -o /dev/null -X POST "$RENDER_DEPLOY_HOOK")
          if [ "$response" -eq 200 ]; then
            echo "Render deploy triggered successfully."
          else
            echo "Failed to trigger Render deploy. HTTP status: $response"
            exit 1
          fi
  
  e2e-tests:
    needs: deploy-render
    if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: e2e-tests
    env:
      API_BASE_URL: https://render.sirius-crm.online
      TEST_USER: giorgosts
      TEST_PASS: tsantekidis
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run test:e2e
  
  build-and-push:
    #needs: e2e-tests
    #if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: push-image-ecr
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sirius-crm-server
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-aws:
    needs: build-and-push
    #if: ${{ needs.unit-tests.result == 'success' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: aws
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 081009271230.dkr.ecr.eu-central-1.amazonaws.com
            cd sirius-crm
            echo IMAGE_TAG=${{ github.sha }} > .env_image_tag
            docker compose --env-file .env_image_tag pull
            docker compose --env-file .env_image_tag up -d 

